-- scripts/create-products-table.sql

-- Create the products table
CREATE TABLE public.products (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price INT NOT NULL,
    category VARCHAR(255) NOT NULL,
    description TEXT,
    size VARCHAR(255), -- Assuming size is a single string like "S, M, L, XL" or "M, L, XL"
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Optional: Add RLS (Row Level Security) policies if you plan to use Supabase Auth
-- For now, we'll make it publicly readable for simplicity in this example.
-- In a real app, you'd want more granular control.
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON public.products
FOR SELECT USING (true);

-- Insert some sample data
INSERT INTO public.products (name, price, category, description, size, image_url) VALUES
('Remera Básica Blanca', 2500, 'remeras', 'Remera básica de algodón 100%, perfecta para el día a día. Corte clásico y suave al tacto.', 'S, M, L, XL', '/placeholder.svg?height=200&width=200&text=Remera Blanca'),
('Remera Estampada Negra', 3200, 'remeras', 'Remera con estampado moderno, ideal para looks casuales. Tela de alta calidad.', 'S, M, L, XL', '/placeholder.svg?height=200&width=200&text=Remera Negra'),
('Remera Oversize Gris', 2800, 'remeras', 'Remera oversize de algodón premium. Estilo relajado y cómodo.', 'M, L, XL', '/placeholder.svg?height=200&width=200&text=Remera Gris'),
('Remera Rayada Azul', 2900, 'remeras', 'Remera con rayas clásicas, perfecta para un look náutico y fresco.', 'S, M, L, XL', '/placeholder.svg?height=200&width=200&text=Remera Azul'),
('Buzo Canguro Negro', 4500, 'buzos', 'Buzo canguro con capucha y bolsillo frontal. Ideal para el frío.', 'S, M, L, XL', '/placeholder.svg?height=200&width=200&text=Buzo Negro'),
('Buzo Crewneck Beige', 4200, 'buzos', 'Buzo sin capucha de cuello redondo. Tejido suave y cálido.', 'S, M, L, XL', '/placeholder.svg?height=200&width=200&text=Buzo Beige'),
('Pantalón Cargo Negro', 3800, 'pantalones', 'Pantalón cargo con múltiples bolsillos. Estilo utilitario y moderno.', 'S, M, L, XL', '/placeholder.svg?height=200&width=200&text=Pantalon Negro');
